name: parsers
version: 0.13.7
author: Paul Brauner <polux@google.com>
description: Parser combinators for Dart
homepage: https://github.com/polux/parsers
documentation: http://goo.gl/ZNqdEH
environment:
  sdk: '>=0.4.7'
dependencies:
  persistent: '>=0.7.0 <0.8.0'
dev_dependencies:
  unittest: any
