name: parsers
version: 0.11.4
author: Paul Brauner <polux@google.com>
description: Parser combinators for Dart
homepage: http://code.google.com/p/parsers/
documentation: http://goo.gl/OqXXb
dependencies:
  persistent: any
dev_dependencies:
  unittest: any
