name: parsers
description: Parser combinators for Dart.
version: 0.7.0
author: Paul Brauner <polux@google.com>
homepage: http://code.google.com/p/parsers/
dependencies:
  unittest: any
  persistent: any
