name: parsers
version: 0.12.4
author: Paul Brauner <polux@google.com>
description: Parser combinators for Dart
homepage: http://code.google.com/p/parsers/
documentation: http://goo.gl/OqXXb
environment:
  sdk: '>=0.4.7'
dependencies:
  persistent: '>=0.7.0 <0.8.0'
dev_dependencies:
  unittest: any
