name: parsers
description: Parser combinators for Dart
version: 0.11.3
author: Paul Brauner <polux@google.com>
homepage: http://code.google.com/p/parsers/
documentation: http://goo.gl/OqXXb
dependencies:
  unittest: any
  persistent: any
